project:
  type: website
  output-dir: docs

website:
  title: "Reyajul Hasan Leon"
  favicon: "/_assets/images/logofsu.png"
  open-graph: true
  navbar:
    background: "#782F40"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



